# Generated by Django 5.1.6 on 2025-04-22 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feel',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_user_post_feel'),
        ),
    ]
